[package]
name = "project_puppets"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.7.0", features = ["dynamic"] }
bevy-inspector-egui = "0.10.0"
bevy_rapier2d = "0.13.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
